"""Exercise the running API using synthetic, uniquely named accounts."""

import argparse
import json
import os
import re
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import HTTPRedirectHandler, Request, build_opener


class NoRedirects(HTTPRedirectHandler):
    # Never forward the reviewer's Authorization header to a redirect target.
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def check(condition, message):
    if not condition:
        raise RuntimeError(message)


def demo_token():
    """Read one reviewer token; process environment wins over the script's local .env."""
    token = os.environ.get("LEDGER_API_TOKEN")
    if token is None:
        path = Path(__file__).with_name(".env")
        values = []
        if path.is_file():
            for line in path.read_text(encoding="utf-8-sig").splitlines():
                if line.strip() and not line.lstrip().startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    if key.strip() == "LEDGER_API_TOKEN":
                        values.append(value.strip())
        if len(values) > 1:
            raise ValueError("local .env must contain only one LEDGER_API_TOKEN assignment")
        token = values[0] if values else None
        if token and len(token) > 1 and token[0] == token[-1] and token[0] in ("'", '"'):
            token = token[1:-1]
    if token is not None and not re.fullmatch(r"[\x21-\x7e]{32,255}", token):
        raise ValueError("LEDGER_API_TOKEN must contain 32-255 printable ASCII characters without spaces; use only the token, not Bearer. Process environment overrides .env.")
    return token


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default="http://127.0.0.1:8000", help="local API or Railway HTTPS URL")
    parser.add_argument("--prefix", help="account prefix (generated by default)")
    parser.add_argument("--check-only", action="store_true", help="verify a previous demo after a server restart")
    args = parser.parse_args()
    url = urlsplit(args.url)
    if url.scheme not in {"http", "https"} or not url.hostname or url.username or url.password or url.path not in {"", "/"} or url.query or url.fragment:
        parser.error("--url must be an HTTP(S) origin without credentials, a path, query or fragment")
    if url.scheme == "http" and url.hostname not in {"127.0.0.1", "localhost", "::1"}:
        parser.error("use HTTPS for a remote demo")
    if args.check_only and not args.prefix:
        parser.error("--check-only requires the --prefix from a previous demo")
    prefix = args.prefix or "demo-" + uuid.uuid4().hex[:12]
    if not re.fullmatch(r"[A-Za-z0-9_-]{1,100}", prefix):
        parser.error("--prefix must contain 1-100 ASCII letters, digits, underscores or hyphens")
    base = args.url.rstrip("/")
    token = demo_token()
    if url.hostname not in {"127.0.0.1", "localhost", "::1"} and not token:
        parser.error("remote demos require LEDGER_API_TOKEN in the process environment or a .env file next to demo.py")
    opener = build_opener(NoRedirects())

    def request(method, path, body=None, key=None, expected=None):
        headers = {"Content-Type": "application/json"}
        if token:
            headers["Authorization"] = "Bearer " + token
        if key:
            headers["Idempotency-Key"] = key
        data = None if body is None else json.dumps(body).encode()
        try:
            response = opener.open(Request(base + path, data, headers, method=method), timeout=15)
        except HTTPError as error:
            response = error
        with response:
            status = response.code
            result = json.loads(response.read())
        wanted = expected if expected is not None else (200 if method == "GET" else 201)
        if status == 401 and wanted != 401:
            raise RuntimeError("authentication rejected: verify the active deployment's token; LEDGER_API_TOKEN in the process environment overrides the local .env file")
        check(status == wanted, f"{method} {path}: expected {wanted}, got {status}: {result}")
        return result

    cash, reserve, euro = (prefix + suffix for suffix in ("-cash", "-reserve", "-euro"))
    payment = {"source_account": cash, "destination_account": reserve, "amount": "30.00"}
    key = prefix + "-payment"

    def balances(expected):
        actual = tuple(request("GET", "/accounts/" + account)["balance"] for account in (cash, reserve, euro))
        check(actual == expected, f"balance mismatch: {actual}, expected {expected}")
        print(f"  USD cash={actual[0]}, USD reserve={actual[1]}, EUR={actual[2]}")

    check(request("GET", "/health")["status"] == "ok", "service is not ready")
    print(f"Demo prefix: {prefix}")
    if not args.check_only:
        for account, code, opening in ((cash, "USD", "100.00"), (reserve, "USD", "0"), (euro, "EUR", "0")):
            request("POST", "/accounts", {"id": account, "currency": code, "opening_balance": opening})
        print("PASS: account creation")
        posted = request("POST", "/transactions", payment, key)
        balances(("70.00", "30.00", "0.00"))
        check(request("POST", "/transactions", payment, key) == posted, "retry changed the response")
        print("PASS: transfer and identical idempotent retry")
        for body, retry_key, status in (
            ({**payment, "amount": "31.00"}, key, 409),
            ({**payment, "amount": "70.01"}, prefix + "-overdraft", 409),
            ({**payment, "amount": "0.001"}, prefix + "-fraction", 400),
        ):
            request("POST", "/transactions", body, retry_key, status)
        balances(("70.00", "30.00", "0.00"))
        print("PASS: conflicting retry, overdraft and fractional-cent rejection")
        fx = request("POST", "/transactions", {"source_account": cash, "destination_account": euro, "amount": "10.00", "exchange_rate": "0.91"}, prefix + "-fx")
        check(fx["destination"]["amount"] == "9.10", "incorrect FX result")
        balances(("60.00", "30.00", "9.10"))
        print("PASS: USD 10.00 converts to EUR 9.10")
        for original, reversal_key in ((posted, prefix + "-reverse-payment"), (fx, prefix + "-reverse-fx")):
            path = f'/transactions/{original["id"]}/reversal'
            reversal = request("POST", path, {}, reversal_key)
            check(reversal["reversal_of"] == original["id"], "incorrect reversal link")
            check(request("POST", path, {}, reversal_key) == reversal, "reversal retry changed the response")
            request("POST", path, {}, reversal_key + "-different", 409)
        print("PASS: exact reversals, reversal retries and double-reversal rejection")
    else:
        # Replaying the original key after its reversal must not move money again.
        posted = request("POST", "/transactions", payment, key)
        check(posted["source"]["amount"] == "30.00", "persisted response is incorrect")
        print("PASS: persisted original transaction remains idempotent")
    balances(("100.00", "0.00", "0.00"))
    first = request("GET", f"/accounts/{cash}/transactions?limit=2")
    check(len(first["transactions"]) == 2 and first["next_cursor"], "incorrect first history page")
    second = request("GET", f"/accounts/{cash}/transactions?limit=2&after={first['next_cursor']}")
    history = first["transactions"] + second["transactions"]
    check([item["account_amount"] for item in history] == ["-30.00", "-10.00", "30.00", "10.00"] and second["next_cursor"] is None, "incorrect ordered or paginated history")
    check(history[0]["id"] == posted["id"], "persisted transaction ID changed")
    check(request("GET", "/integrity")["ok"], "global ledger integrity check failed")
    print("PASS: ordered history, pagination and global integrity")
    if not args.check_only:
        current = datetime.now(timezone.utc).replace(day=1)
        month = (current - timedelta(days=1)).strftime("%Y-%m")
        report = request("POST", "/reconciliations/" + month)
        check(report["ok"], "month-end reconciliation failed")
        check(request("GET", "/reconciliations/" + report["id"]) == report, "stored reconciliation changed")
        request("POST", "/reconciliations/" + current.strftime("%Y-%m"), expected=409)
        print(f"PASS: completed UTC month {month}, stored report and current-month rejection")
    print("ALL CHECKS PASSED")
    print("After restarting/redeploying with the same database, run:")
    print(f"python demo.py --url {base} --prefix {prefix} --check-only")
    print("Synthetic accounts and immutable records are kept; a new run uses a new prefix.")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, URLError, TimeoutError, OSError, ValueError) as error:
        print(f"DEMO FAILED: {error}", file=sys.stderr)
        sys.exit(1)
